name: ESP32 Tests

on:
  pull_request:
    paths:
      - 'esp32/**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  esp32Test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install PlatformIO
      run: |
          cd esp32
          pip install platformio

    - name: Compile ESP32 firmware
      run: |
          cd esp32
          pio run